title: CINO MY LIFE
author: GitHub User-lakshita
email: lakshitabeniwalm143@gmail.com
description: >  LIFE IS NOT CRUEL BUT CURLEY :
### life it enjoying the way you like
  
# social links
twitter_username: none
github_username:   LAKSHITABENIWAL

show_excerpts:false
theme-minima
